### ISSUE TITLE
python3でCSA.pyが動かない

### ISSUE THREAD

**Issue by YusukeSuzuki** [gunyarakun/python-shogi#1]
python3 で random_csa_tcp_match を動かそうとすると以下のエラーが出ます。

```
Traceback (most recent call last):
  File "./random_csa_tcp_match", line 23, in <module>
    ct.login(sys.argv[2], sys.argv[3])
  File "......./python-shogi/shogi/CSA.py", line 377, in login
    line = self.command('LOGIN {0} {1}'.format(username, password))
  File "......./python-shogi/shogi/CSA.py", line 335, in command
    self.write(command + '\n')
  File "......./python-shogi/shogi/CSA.py", line 340, in write
    self.socket.sendall(buf)
TypeError: a bytes-like object is required, not 'str'
```

bufにencode(), decode()をつければpython3でも動きますがpython2と互換のコードになっているかわからずプルリクエストが出せません。

**Comment by gunyarakun** [comment]
ついに気がついた人が現れました。
https://twitter.com/tasukuchan/status/612723416492212225

b9b719f340365fe9ccc8357b19d2b8343cc41614 で修正しました。
